### ISSUE TITLE
Add facade for MIMO component

### ISSUE THREAD

**Issue by henhuy** [sedos-project/oemof.industry#2]
We need an oemof.tabular facade for MIMO component which reads tabular data and generates MIMO component from it.
Special case for MIMO component is variable number of input/output buses and dynamic grouping of those buses.
Following naming conventions are implicitly used for reading out facade parameters:
- `from_bus_{counter}`
- `to_bus_{counter}`
- `group_{counter}`
- `conversion_factor_{bus}`
- `flow_share_{type}_{bus}`
- `emission_factor_{from_bus}_{to_bus}` (Attention here! as detecting from and to bus can lead to errors,if bus names contain underscores!)

**TODOs:**
- [ ] Implement parameters from above
- [ ] Add investment parameters
- [ ] Write tests in `test_datapackage`

**Comment by SabineHaas** [comment]
- [x] get running / reproduce
- [x] basic test func with steel example 
- [x] what to look out for when using lists in csv
- [x] Adapt MIMO facade
   - [x] implement groups for `from_bus`and `to_bus`
   - [x] pre-init and drop new parameters `conversion_factors`, `emission_factors`, and `flow_shares` (**groups by naming convention**: instead of `bus` there can be named the `group`. )
      - [x] `conversion_factors`
      - [x] `emission_factors`
      - [x] `flow_shares`
   - [ ] optional: docstring/comments
- [x] if needed, extend existing steel example tests/datapackages/mimo/data (if necessary see SEDOS_Modellstruktur.xlsx Processes_steel_industry_2), see note below
- [ ] write tests: assert data structure, optional: assert emissions
   - [ ] fix: is infeasible when emission_factor for n2o exists
   - [ ] rename busses to test bus combinations
- [ ] fixes
   - [x] fix ValueError when using sequence for flow_shares, see [error_msg.txt](https://github.com/sedos-project/oemof.industry/files/14236953/error_msg.txt)
    `ValueError: All arrays must be of the same length`    
    Note: the problem is infeasible, when adding the flow_shares for H2 as sequence (also if ch4, the other carrier in the group, is not limited)
   - [ ] From commit 663ff7e on I get the following warning (when adding more input busses to the test case)
    `WARNING Element (MIMO(carrier='exo_steel', tech='mimo'), 'group_0', 0, 8754) already exists in Set OrderedScalarSet; no action taken` 
    It is raised in these lines
    https://github.com/sedos-project/oemof.industry/blob/98b50d1e3a704d462675e6e5348aadbb396113fe/oemof_industry/mimo_converter.py#L433-L441


**Note**: The test case should include groups and single inputs/outputs in: `inputs`, `outputs`, `emission_factors` and `emission_factors`, example for inputs:

      ```
      inputs={
          "gas": {
          gas_1: Flow(),
          gas_2: Flow(),
          },
          single_input: Flow(),
      }
      ```

**[I]** new: MIMO dataclass - like a "pre-init": everything that causes problems in the original data class is already initialized here and then dropped from the kwargs

**Comment by SabineHaas** [comment]
Information about lists in csvs:

- depending on programm used to edit the file see https://github.com/rl-institut/multi-vector-simulator/issues/279
- seems to be an issue when using only a list (we are using a list in a dict)

So I'd say we can go for the option `{"gas": ["electricity", "sec_coke_oven_gas"]}`.

**Comment by SabineHaas** [comment]
Hey @henhuy , I have two questions:

- Did you want to make further use of the test example? I am thinking to build an example that contains all possible cases concerning grouped and non-grouped parameters, see **"Note"** above. However this would be no realistic case. 
- As far as I could see in the examples `efficiency` seems to be a typical name for conversion_factor/efficiency in oemof.tabular. What do you think about going for `efficiency_{bus}` instead of `conversion_factor_{bus}`, therefore?

**Comment by henhuy** [comment]
> * Did you want to make further use of the test example? I am thinking to build an example that contains all possible cases concerning grouped and non-grouped parameters, see **"Note"** above. However this would be no realistic case.

Go for it! Feel free ;)

**Comment by henhuy** [comment]
> * As far as I could see in the examples `efficiency` seems to be a typical name for conversion_factor/efficiency in oemof.tabular. What do you think about going for `efficiency_{bus}` instead of `conversion_factor_{bus}`, therefore?

No problem - we must adapt mapping in `data_adapter` anyway.

**Comment by henhuy** [comment]
We also need typical investment parameters!
Aka `lifetime`, `capacity_cost`, `variable_cost` etc.
You could look at other Facades to copy those.
We still have to look how to put those costs into MIMO, as normally those are put on a Flow - but we have to check which flow is the "primary" flow. We can discuss that bilaterally.

**Comment by SabineHaas** [comment]
Hey  @henhuy , could you help me out on these two points?

> fixes
> 
>     * [ ]  fix ValueError when using sequence for flow_shares, see [error_msg.txt](https://github.com/sedos-project/oemof.industry/files/14236953/error_msg.txt)
>       `ValueError: All arrays must be of the same length`
>       Note: the problem is infeasible, when adding the flow_shares for H2 as sequence (also if ch4, the other carrier in the group, is not limited)
> 
>     * [ ]  From commit [663ff7e](https://github.com/sedos-project/oemof.industry/commit/663ff7e001a826e7fd69f22a3268aaff41e90fa7) on I get the following warning (when adding more input busses to the test case)
>       `WARNING Element (MIMO(carrier='exo_steel', tech='mimo'), 'group_0', 0, 8754) already exists in Set OrderedScalarSet; no action taken`
>       It is raised in these lines
>       https://github.com/sedos-project/oemof.industry/blob/98b50d1e3a704d462675e6e5348aadbb396113fe/oemof_industry/mimo_converter.py#L433-L441
